# Shell variables
# Generated by 'wal'
wallpaper='/home/kyn/Pictures/Wallpapers/Skyairt7.png'

# Special
background='#0c0f18'
foreground='#9baabe'
cursor='#9baabe'

# Colors
color0='#0c0f18'
color1='#234E64'
color2='#614C68'
color3='#AB4A41'
color4='#A14E5F'
color5='#DC5F5B'
color6='#F0915A'
color7='#9baabe'
color8='#6c7685'
color9='#234E64'
color10='#614C68'
color11='#AB4A41'
color12='#A14E5F'
color13='#DC5F5B'
color14='#F0915A'
color15='#9baabe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
