# Shell variables
# Generated by 'wal'
wallpaper='/home/kyn/Pictures/Wallpapers/Kame_house1920x1080.jpg'

# Special
background='#121948'
foreground='#e9cbc0'
cursor='#e9cbc0'

# Colors
color0='#121948'
color1='#324DA0'
color2='#5867A2'
color3='#9C748C'
color4='#7785A9'
color5='#6790DB'
color6='#AEA5BA'
color7='#e9cbc0'
color8='#a38e86'
color9='#324DA0'
color10='#5867A2'
color11='#9C748C'
color12='#7785A9'
color13='#6790DB'
color14='#AEA5BA'
color15='#e9cbc0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
