--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kyn/Pictures/Wallpapers/Kame_house1920x1080.jpg"

-- Special
background="#121948"
foreground="#e9cbc0"
cursor="#e9cbc0"

-- Colors
color0="#121948"
color1="#324DA0"
color2="#5867A2"
color3="#9C748C"
color4="#7785A9"
color5="#6790DB"
color6="#AEA5BA"
color7="#e9cbc0"
color8="#a38e86"
color9="#324DA0"
color10="#5867A2"
color11="#9C748C"
color12="#7785A9"
color13="#6790DB"
color14="#AEA5BA"
color15="#e9cbc0"
