--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kyn/Pictures/Wallpapers/goku-moon.jpg"

-- Special
background="#080C15"
foreground="#e3d5cc"
cursor="#e3d5cc"

-- Colors
color0="#080C15"
color1="#A86154"
color2="#D7976B"
color3="#5F7389"
color4="#8B7B87"
color5="#6C8EA5"
color6="#9F989F"
color7="#e3d5cc"
color8="#9e958e"
color9="#A86154"
color10="#D7976B"
color11="#5F7389"
color12="#8B7B87"
color13="#6C8EA5"
color14="#9F989F"
color15="#e3d5cc"
