# Shell variables
# Generated by 'wal'
wallpaper='/home/kyn/Pictures/Wallpapers/goku-moon.jpg'

# Special
background='#080C15'
foreground='#e3d5cc'
cursor='#e3d5cc'

# Colors
color0='#080C15'
color1='#A86154'
color2='#D7976B'
color3='#5F7389'
color4='#8B7B87'
color5='#6C8EA5'
color6='#9F989F'
color7='#e3d5cc'
color8='#9e958e'
color9='#A86154'
color10='#D7976B'
color11='#5F7389'
color12='#8B7B87'
color13='#6C8EA5'
color14='#9F989F'
color15='#e3d5cc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
