--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kyn/Pictures/Wallpapers/Skyairt7.png"

-- Special
background="#0c0f18"
foreground="#9baabe"
cursor="#9baabe"

-- Colors
color0="#0c0f18"
color1="#234E64"
color2="#614C68"
color3="#AB4A41"
color4="#A14E5F"
color5="#DC5F5B"
color6="#F0915A"
color7="#9baabe"
color8="#6c7685"
color9="#234E64"
color10="#614C68"
color11="#AB4A41"
color12="#A14E5F"
color13="#DC5F5B"
color14="#F0915A"
color15="#9baabe"
